os:
  - linux
  - osx

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: phpunit --configuration ./tests/phpunit.xml

matrix:
  allow_failures:
    - php: nightly
