os:
  - linux
  - osx

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

install:
  - composer self-update
  - composer install --no-interaction

script: phpunit --configuration ./tests/phpunit.xml

matrix:
  allow_failures:
    - php: nightly
