os:
  - linux

sudo: required

language: php

php:
  - 7.0

services:
  - docker

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - docker pull epcallan/php7-testing-phpunit:7.0-phpunit5
  - docker pull epcallan/php7-testing-phpunit:7.1-phpunit5

script:
  - docker run -v $(pwd):/app epcallan/php7-testing-phpunit:7.0-phpunit5 --configuration /app/tests/phpunit.xml
  - docker run -v $(pwd):/app epcallan/php7-testing-phpunit:7.1-phpunit5 --configuration /app/tests/phpunit.xml

notifications:
  email:
    on_success: never
    on_failure: always
